version: '3'
services:

  # PHP Service
  php-fpm:
    build:
      context: ""
      dockerfile: ./php-fpm/Dockerfile
      args:
        username: ${USER_NAME}
        useruid: ${USER_UID}
    image: php:8.0-fpm
    container_name: php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: ${APP_NAME}
      SERVICE_TAGS: dev
      PHP_IDE_CONFIG: "serverName=${APP_NAME}"
      XDEBUG_CONFIG: "idekey=PHPSTORM"
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    networks:
      blepi:
        ipv4_address: 80.10.0.105

  # Nginx Service
  webserver:
    image: nginx:1.19.0
    container_name: web-server
    restart: unless-stopped
    tty: true
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    volumes:
      - ../:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      blepi:
        ipv4_address: 80.10.0.104

  #Postgres Service
  postgres:
    build:
      context: ""
      dockerfile: ./postgres-dockerfile/Dockerfile
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PORT=${DB_PORT}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      blepi:
        ipv4_address: 80.10.0.110

networks:
  blepi:
    driver: bridge
    ipam:
      config:
        - subnet: 80.10.0.0/24
